spring:
  data:
   redis:
    host: xxx.xxx.xxx.xxx
    port: 6379
    password: xxxxxx
    lettuce:
      pool:
        # 最大连接数
        max-active: 10
        # 最大闲置数
        max-idle: 10
        # 最小闲置数
        min-idle: 1
        # 最长等待时间
        time-between-eviction-runs: 10s